### PR TITLE
FIX: setting refreshInterval option to <= 0 disables polling

### PR DESCRIPTION
**Pull request by artemivanyk**
Hi Jan,

zero is a falsy value in JS, so `parseInt(0)` in this case sets the interval to default value.

Thanks for the great work you are doing!  :-)

### CODE REVIEW

**Comment by janpaepke** [comment]
Nice catch.
You could use `_util.type.Number(ri)` to validate it using internal functions.
What do you think?

**Comment by artemivanyk** [comment]
Sure. I’ve edited the line. (Sorry, haven’t had time to dig into the codebase)

**Comment by janpaepke** [comment]
I didn't expect you to, so no reason to be sorry. :)
Most people don't even bother looking at the source, so thx 4 that.

Still it would be super awesome is if you could add a test for the new fix.
If you don't have the time I can take care of it, but my time is sort of short at the moment.

**Comment by janpaepke** [comment]
Cool, thx. Nice work!
One more thing though: Pls only include source files in your commit, not the build files.
I'll merge right after :)

**Comment by artemivanyk** [comment]
Done :-)

**Comment by janpaepke** [comment]
thx, man! :)

**Pull request merged**
