### PR TITLE
Increase fps limit for mobile support(advance) example.

### PR DESCRIPTION
**Pull request by nonjene**
as iScroll's scroll event is fired by raf,  update should be immediately. If nest one more raf, the max fps will be only 30.

### CODE REVIEW

**Comment by janpaepke** [comment]
won't this decrease performance?

**Comment by nonjene** [comment]
fps on 30 will be laggy. 
I create a [reproduction](https://codepen.io/nonjene/pen/WayROP) of the issue.

**Comment by janpaepke** [comment]
I think I understand.
Awesome catch! Thanks for the great reproduction!

Would you be interested to contribute more to SM?

**Comment by nonjene** [comment]
yeah I would love to 😄

**Pull request merged**
